### ISSUE TITLE
#19 HELP1

### ISSUE THREAD

**Issue by Jrjuniorjr** [felixruan09/FWInternetBanking#19]
setSaldo em observação, pois eu acho errado ter um setSaldo, entretanto não é possível fazer com que o debitar da ContaImposto sem o setSaldo, pois o saldo está private. Se eu trocar para protected, quebra o principio de encapsulamento.

**Comment by LLealL** [comment]
Protected void SetSaldo() , solução temporária pra preservar o encapsulamento do acesso ao saldo. Até decidirmos como arrumar.

**Comment by felixruan09** [comment]
sob hipótese alguma, um atributo private consegue ser visualizado por outra classe, mesmo que nesse caso a classe seja uma filha. Protected SetSaldo() é a solução não temporária, mas aparentemente a definitiva para esse problema.
