### ISSUE TITLE
#32 HELP2

### ISSUE THREAD

**Issue by Jrjuniorjr** [felixruan09/FWInternetBanking#33]
Galera, tem que ver como vai pegar o tipo, tanto de conta, quanto de cliente, do banco, pois no banco ele ta armazenando um inteiro, e na nossa aplicação, um enum.

**Comment by LLealL** [comment]
Na classe do repositorio terá que fazer a conversão do enum pra esse tinyint.

**Comment by Jrjuniorjr** [comment]
E depois, como voltar? não tem como fazer essa conversão, a não ser com switch ou if-else.

**Comment by LLealL** [comment]
por mim faria o if-else mesmo , apesar de sujar o código , é a única solução que vejo.

**Comment by LLealL** [comment]
Solução: Faz uso de Factory
