### ISSUE TITLE
ERROR DE BUILD AO TESTAR JDBC

### ISSUE THREAD

**Issue by LLealL** [felixruan09/FWInternetBanking#51]
então, pelo que eu consegui identificar até agora , o erro está no JDBCConnectionUtil , pois não está conseguindo carregar o driver do JDBC  pelo properties. podemos dar bola pra frente nesse JDBC e trabalhar no que falta , ou perder mais tempo tentando arrumar isso. Posso também estar tentando usar sem saber direito.

**Comment by Jrjuniorjr** [comment]
Talvez nao esta pegando pq no banco precisa de id, só q na aplicação da gente nao ta tratando esse id.
